name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt yamllint jsonschema

      - name: YAML lint
        run: yamllint .

      - name: Validate prompt schema
        run: |
          for file in $(find prompts -name '*.prompt.yaml' -print); do
            jsonschema -i "$file" prompt.schema.yaml
          done

      - name: Regenerate category indexes
        run: python scripts/generate_index.py

      - name: Check for uncommitted changes
        run: git diff --exit-code
